## Numpy 核心

### 1.NumPy 基础

- 学习内容:

    - 了解 NumPy ndarray (N-dimensional array) 的概念，它是 NumPy 的核心数据结构。

    - 如何使用 np.array() 从 Python 列表或元组创建数组。

    - 理解数组的 ndim (维度数量)、shape (形状)、size (元素总数) 和 dtype (数据类型)。

In [2]:
import numpy as np
print(np.__version__)

1.24.3


In [3]:
# 创建一维数组
arr1 = np.array([1, 2, 3, 4, 5])
print("arr1:", arr1)
print("ndim:", arr1.ndim, "shape:", arr1.shape, "size:", arr1.size, "dtype:", arr1.dtype)

# 创建二维数组 (矩阵)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("\narr2:\n", arr2)
print("ndim:", arr2.ndim, "shape:", arr2.shape, "size:", arr2.size, "dtype:", arr2.dtype)

# 创建三维数组 (图像数据常为三维)
# 模拟一个 2x2 像素的 RGB 图像 (高x宽x通道)
img_tensor = np.array([
    [[255, 0, 0], [0, 255, 0]],  # 第一行像素 (红, 绿)
    [[0, 0, 255], [255, 255, 0]] # 第二行像素 (蓝, 黄)
])
print("\nimg_tensor:\n", img_tensor)
print("ndim:", img_tensor.ndim, "shape:", img_tensor.shape, "size:", img_tensor.size, "dtype:", img_tensor.dtype)

arr1: [1 2 3 4 5]
ndim: 1 shape: (5,) size: 5 dtype: int32

arr2:
 [[1 2 3]
 [4 5 6]]
ndim: 2 shape: (2, 3) size: 6 dtype: int32

img_tensor:
 [[[255   0   0]
  [  0 255   0]]

 [[  0   0 255]
  [255 255   0]]]
ndim: 3 shape: (2, 2, 3) size: 12 dtype: int32


### 2.数组创建方法
- 学习内容：
    - 理解 np.zeros(), np.ones(), np.empty() 用于创建指定形状和数据类型的数组。
    - np.arange() 和 np.linspace() 用于创建等差数列。
    - np.random 模块用于创建随机数组。


In [4]:
# 全零数组
zeros_arr = np.zeros((3,4));
print("\n zeros_arr: \n",zeros_arr);

# allones array
ones_arr = np.ones((2,6));
print("\n ones_arr: \n",ones_arr);

#random array
rand_arr = np.random.rand(2,3);
rand_arr_1 = np.random.random(12);
print("\n rand_arr: \n",rand_arr); # a random number between 0 and 1
print("\n rand_arr_1: \n",rand_arr_1);

# 等差数列
range_arr = np.arange(0, 10, 2) # from 0 to 10, step size equals 2.
print("\nrange_arr:", range_arr)

linspace_arr = np.linspace(0, 1, 5) # from 0 to 1, choose 5 points evenly
print("linspace_arr:", linspace_arr)


 zeros_arr: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 ones_arr: 
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]

 rand_arr: 
 [[0.98097079 0.04541015 0.52602282]
 [0.33546392 0.74449566 0.46485487]]

 rand_arr_1: 
 [0.3019475  0.07809184 0.2262239  0.47026684 0.66649158 0.06416107
 0.34176695 0.29030296 0.48801337 0.56627263 0.28992894 0.39575855]

range_arr: [0 2 4 6 8]
linspace_arr: [0.   0.25 0.5  0.75 1.  ]


### 3.数组索引、切片与形状操作
- 学习内容：
    - 索引: 类似于 Python 列表，但支持多维索引。

    - 切片: 使用 : 进行切片，可以提取数组的子集。

    - 布尔索引: 使用布尔数组作为索引进行条件筛选。

    - 花式索引: 使用整数数组作为索引，可以获取不连续的元素。

    - 形状操作: reshape(), resize(), flatten(), ravel(), transpose(), T (转置)。

In [5]:
arr = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print("Original arr:\n",arr)

# 索引
print("\nElement at (0, 0):", arr[0, 0]) # 访问第一行第一列
print("Second row:", arr[1]) # 访问第二行

# 切片
print("\nFirst two rows, all columns: \n", arr[:2, :])
print("All rows, last column: \n", arr[:, 2])
print("Sub-array(middle 2×2): \n", arr[0:2, 1:3]) #提取2×2子数组

# 布尔索引 (找出所有大于5的元素)
print("\nElements > 5:", arr[arr > 5])

# 花式索引 (访问 (0,0), (1,2), (2,1) 位置的元素)
print("Fancy indexing:", arr[[0, 1, 2], [0, 2, 1]])

# 形状操作
# reshape: 不改变数据，只改变视图
reshaped_arr = arr.reshape(1, 9)
print("\nReshaped to 1x9:\n", reshaped_arr)

# transpose: 转置 (行变列，列变行)
transposed_arr = arr.T
print("Transposed arr:\n", transposed_arr)

# flatten: 将多维数组展平为一维数组 (返回副本)
flat_arr = arr.flatten()
print("Flattened arr:", flat_arr)

# ravel: 将多维数组展平为一维数组 (返回视图或副本)
raveled_arr = arr.ravel()
print("Raveled arr:", raveled_arr)


Original arr:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Element at (0, 0): 1
Second row: [4 5 6]

First two rows, all columns: 
 [[1 2 3]
 [4 5 6]]
All rows, last column: 
 [3 6 9]
Sub-array(middle 2×2): 
 [[2 3]
 [5 6]]

Elements > 5: [6 7 8 9]
Fancy indexing: [1 6 8]

Reshaped to 1x9:
 [[1 2 3 4 5 6 7 8 9]]
Transposed arr:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Flattened arr: [1 2 3 4 5 6 7 8 9]
Raveled arr: [1 2 3 4 5 6 7 8 9]


### 小练习
- 尝试将一个模拟的 RGB 图像（例如 10x10x3 的 NumPy 数组）进行切片，提取出红色通道或某个区域的像素。
- 思考 reshape() 和 resize() 的区别，以及 flatten() 和 ravel() 的区别。

In [6]:
RGB = np.random.randint(0,256,size = (10, 10, 3), dtype=np.uint8)
print(RGB)
RED_slice = RGB[:,:,0]
print(RED_slice.shape)
print("RED_slice: \n", RED_slice)


[[[124  74 113]
  [160  44  71]
  [ 45  34  47]
  [207  31 132]
  [217  89 117]
  [ 64  91  94]
  [133 113   0]
  [123 167 171]
  [155  38  96]
  [136 110 215]]

 [[154 116 191]
  [233 156 186]
  [162 143  79]
  [ 89  64 157]
  [187 106 179]
  [ 12 232 171]
  [ 51  71  48]
  [ 58 162 111]
  [  6   0  32]
  [ 36 204 199]]

 [[ 60 252  56]
  [ 23 194  82]
  [219  51 141]
  [252 142  53]
  [141  77  48]
  [200 214 194]
  [101  42 245]
  [ 32 171 193]
  [  4 251  91]
  [214  87 165]]

 [[ 78 234 199]
  [137  60  24]
  [113 241 147]
  [  4 128  60]
  [  8 215 123]
  [100  97 232]
  [187  16  61]
  [ 80  12  60]
  [ 26 167  45]
  [134  21 223]]

 [[ 52  32 186]
  [ 58 166 154]
  [ 66 189 107]
  [ 67 211 209]
  [125 241 141]
  [140  29 121]
  [193  60 143]
  [ 28 226 194]
  [229 181 211]
  [177  64 198]]

 [[203 172  16]
  [ 60  61  79]
  [145  73 144]
  [250 250 240]
  [192  87 111]
  [ 92  80 151]
  [ 21 144 239]
  [215 229 130]
  [237 215 144]
  [184  68 143]]

 [[  5 224 219]
  [  3 178  

In [7]:
X = np.random.random(24)
print(X)
reshaped_X = X.reshape(3,8)
print(reshaped_X)
resized_X = np.resize(X,(3,4))
print(resized_X)

[0.07818377 0.36485419 0.56606248 0.71616202 0.43041263 0.52722555
 0.83696074 0.32021725 0.92535586 0.22959413 0.32765357 0.46800236
 0.1547996  0.96764903 0.97315736 0.02668965 0.44757941 0.0996094
 0.23584466 0.79504612 0.51985729 0.28008851 0.68748046 0.61775348]
[[0.07818377 0.36485419 0.56606248 0.71616202 0.43041263 0.52722555
  0.83696074 0.32021725]
 [0.92535586 0.22959413 0.32765357 0.46800236 0.1547996  0.96764903
  0.97315736 0.02668965]
 [0.44757941 0.0996094  0.23584466 0.79504612 0.51985729 0.28008851
  0.68748046 0.61775348]]
[[0.07818377 0.36485419 0.56606248 0.71616202]
 [0.43041263 0.52722555 0.83696074 0.32021725]
 [0.92535586 0.22959413 0.32765357 0.46800236]]


### 3.NumPy 基本数学运算
- 学习内容: NumPy 数组支持元素级的加减乘除运算，操作符 (+, -, *, /) 会自动对对应位置的元素进行计算。

In [15]:
arr3 = np.array([[1, 2], [3, 4]])
arr4 = np.array([[5, 6], [7, 8]])

print("arr3:\n",arr3)
print("arr4:\n",arr4)

#元素加法
print("\n arr3 + arr4: \n",arr3 + arr4)

# 元素级乘法
print("\n arr3 * arr4: \n",arr3 * arr4)

# 元素级除法
print("\n arr3 / arr4: \n",arr3 / arr4)

# 与标量进行运算
print("\n arr3 + 10 \n",arr3 + 10)

# 其他常用函数：np.sum(), np.mean(), np.max(), np.min(), np.sqrt(), np.exp() 等
print("\n Sum of arr3 elements：\n",np.sum(arr3))
print("\n Mean of arr3 elements：\n",np.mean(arr3))
print("\n Max number of arr3 elements：\n",np.max(arr3))
print("\n Sqrt of arr3 elements：\n",np.sqrt(arr3))


arr3:
 [[1 2]
 [3 4]]
arr4:
 [[5 6]
 [7 8]]

 arr3 + arr4: 
 [[ 6  8]
 [10 12]]

 arr3 * arr4: 
 [[ 5 12]
 [21 32]]

 arr3 / arr4: 
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]

 arr3 + 10 
 [[11 12]
 [13 14]]

 Sum of arr3 elements：
 10

 Mean of arr3 elements：
 2.5

 Max number of arr3 elements：
 4

 Sqrt of arr3 elements：
 [[1.         1.41421356]
 [1.73205081 2.        ]]


### 4.NumPy 广播机制 (Broadcast) (1 小时)

- **学习内容:** 广播是 NumPy 中非常重要的概念，它描述了 NumPy 如何处理形状不同的数组之间的运算。当两个数组的维度不完全匹配时，NumPy 会尝试自动扩展其中一个或两个数组，使其形状兼容，然后进行元素级运算。理解广播机制可以避免很多错误，并写出更简洁的代码。

- **规则:**

    - 如果两个数组的维度数不同，那么维度较少的数组会沿着其左侧（维度较低的一侧）填充一维，直到两个数组的维度数相同。

    - 对于从后往前（或从右往左）遍历的每个维度，如果两个数组在该维度上的大小相同，或者其中一个数组在该维度上的大小为1，则它们是兼容的。

    - 如果一个维度上的大小为1，NumPy 会在该维度上沿着它的大小扩展到另一个数组的大小。

- **记住:** 只有当两个数组在所有维度上都兼容时，才能进行广播

In [17]:
# 示例 1: 向量与矩阵相加
matrix = np.array([[1, 2, 3], [4, 5, 6]]) # 形状 (2, 3)
vector = np.array([10, 20, 30])           # 形状 (3,)

# 广播过程：vector 被视为 [[10, 20, 30], [10, 20, 30]] 后进行元素级加法
print("Matrix:\n", matrix)
print("Vector:", vector)
print("\nMatrix + Vector (broadcast):\n", matrix + vector)

# 示例 2: 不同形状的矩阵相加 (常见错误和正确理解)
matrix_a = np.array([[1, 2], [3, 4]]) # 形状 (2, 2)
col_vector = np.array([[10], [20]])  # 形状 (2, 1)

# 广播过程：col_vector 被扩展为 [[10, 10], [20, 20]]
print("\nMatrix_a:\n", matrix_a)
print("Col_vector:\n", col_vector)
print("\nMatrix_a + Col_vector (broadcast):\n", matrix_a + col_vector)


Matrix:
 [[1 2 3]
 [4 5 6]]
Vector: [10 20 30]

Matrix + Vector (broadcast):
 [[11 22 33]
 [14 25 36]]

Matrix_a:
 [[1 2]
 [3 4]]
Col_vector:
 [[10]
 [20]]

Matrix_a + Col_vector (broadcast):
 [[11 12]
 [23 24]]


### 线性代数基础

- **学习内容:** NumPy 的 np.dot() 或 @ 运算符用于矩阵乘法（点积），**np.linalg** 模块提供了丰富的线性代数函数，如矩阵转置、求逆、行列式、特征值分解、奇异值分解 (SVD) 等。

In [3]:
# 矩阵乘法 (点积)
matrix_A = np.array([[1, 2], [3, 4]])
matrix_B = np.array([[5, 6], [7, 8]])

print("Matrix A:\n", matrix_A)
print("Matrix B:\n", matrix_B)

# 使用 np.dot() 进行矩阵乘法
print("\nMatrix A dot B (np.dot):\n", np.dot(matrix_A, matrix_B))

# Python 3.5+ 推荐使用 @ 运算符进行矩阵乘法
print("Matrix A @ B (@ operator):\n", matrix_A @ matrix_B)

# 向量点积 (dot product)
vec1 = np.array([1, 2, 3])
vec2 = np.array([4, 5, 6])
print("\nVector dot product:", np.dot(vec1, vec2))

# 矩阵转置 (回顾)
print("\nTranspose of Matrix A:\n", matrix_A.T)

# 矩阵求逆 (只适用于方阵且可逆的矩阵)
try:
    inv_matrix_A = np.linalg.inv(matrix_A)
    print("\nInverse of Matrix A:\n", inv_matrix_A)
    # 验证：A @ A_inv 应该是一个单位矩阵
    print("A @ A_inv (should be identity):\n", matrix_A @ inv_matrix_A)
except np.linalg.LinAlgError:
    print("\nMatrix A is singular (不可逆).")

# 行列式
det_A = np.linalg.det(matrix_A)
print("\nDeterminant of Matrix A:", det_A)

# 特征值和特征向量 (Eigenvalues and Eigenvectors)
# 这对于理解 PCA (主成分分析) 和其他降维算法很重要
eigenvalues, eigenvectors = np.linalg.eig(matrix_A)
print("\nEigenvalues of Matrix A:", eigenvalues)
print("Eigenvectors of Matrix A:\n", eigenvectors)

# 奇异值分解 (Singular Value Decomposition - SVD)
# SVD 是张量分解（特别是广义的张量 SVD）的基础，非常重要！
U, s, Vh = np.linalg.svd(matrix_A)
print("\nSVD of Matrix A:")
print("U:\n", U)      # 左奇异向量
print("s:", s)       # 奇异值 (一维数组)
print("Vh:\n", Vh)    # 右奇异向量的共轭转置
# 我们可以用 U, s, Vh 重构原始矩阵 A
# s 需要转换为对角矩阵
sigma = np.zeros((matrix_A.shape[0], matrix_A.shape[1]))
sigma[:matrix_A.shape[0], :matrix_A.shape[0]] = np.diag(s)
reconstructed_A = U @ sigma @ Vh
print("Reconstructed A:\n", reconstructed_A)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]

Matrix A dot B (np.dot):
 [[19 22]
 [43 50]]
Matrix A @ B (@ operator):
 [[19 22]
 [43 50]]

Vector dot product: 32

Transpose of Matrix A:
 [[1 3]
 [2 4]]

Inverse of Matrix A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
A @ A_inv (should be identity):
 [[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]

Determinant of Matrix A: -2.0000000000000004

Eigenvalues of Matrix A: [-0.37228132  5.37228132]
Eigenvectors of Matrix A:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]

SVD of Matrix A:
U:
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
s: [5.4649857  0.36596619]
Vh:
 [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]
Reconstructed A:
 [[1. 2.]
 [3. 4.]]
